### ISSUE TITLE
libminio.sh error

### ISSUE THREAD

**Issue by Fruchtgummi** [bitnami/bitnami-docker-minio#17]
Hey,

i start the docker compose with the follow composing

```
version: '2'

networks:
  app-tier:
    driver: bridge

services:
  minio:
    image: 'bitnami/minio:latest'
    ports:
      - '9000:9000'
    volumes:
      - /srv/minion/data:/data
    environment:
      - MINIO_ACCESS_KEY=yyyyyyyy
      - MINIO_SECRET_KEY=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - MINIO_DEFAULT_BUCKETS=dev:none
    networks:
      - app-tier
```

Error:

/opt/bitnami/scripts/libminio.sh: line 315: /data/.access_key: Permission denied
