### ISSUE TITLE
how to create the compose file with version 3 

### ISSUE THREAD

**Issue by mtariqsajid** [bitnami/bitnami-docker-minio#19]
I try to run this with version 3 in windows 10 but its not working it always through this error
```sh
minio_1  |  20:44:11.86
minio_1  |  20:44:11.86 Welcome to the Bitnami minio container
minio_1  |  20:44:11.86 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-minio
minio_1  |  20:44:11.86 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-minio/issues
minio_1  |  20:44:11.86
minio_1  |  20:44:11.86 INFO  ==> ** Starting MinIO setup **
minio_1  |  20:44:11.90 INFO  ==> Starting MinIO in background...
myapp_1  |  20:44:12.23
myapp_1  |  20:44:12.23 Welcome to the Bitnami minio-client container
myapp_1  |  20:44:12.24 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-minio-client
myapp_1  |  20:44:12.24 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-minio-client/issues
myapp_1  |  20:44:12.24
myapp_1  |  20:44:12.24 INFO  ==> ** Starting MinIO Client setup **
myapp_1  |
myapp_1  |  20:44:12.25 INFO  ==> ** MinIO Client setup finished! **
myapp_1  | mc: <ERROR> `/opt/bitnami/scripts/minio-client/run.sh` is not a recognized command. Get help using `--help` flag.
minioamazons3_myapp_1 exited with code 1
minio_1  |  20:44:21.92 INFO  ==> Adding local Minio host to 'mc' configuration...
minio_1  |  20:44:22.07 INFO  ==> MinIO is already stopped...
minioamazons3_minio_1 exited with code 1`

**Comment by ducky710** [comment]
I'm using it in v3 just like this

```
version: '3'

services:
  minio:
    image: bitnami/minio:latest
    ports:
      - 9000:9000
    environment:
      - MINIO_ACCESS_KEY=12345
      - MINIO_SECRET_KEY=12345
    volumes:
      - /backups/minio/data:/data
    restart: unless-stopped
    ```
