### ISSUE TITLE
Docker distributed mode in different sites

### ISSUE THREAD

**Issue by tom0010** [bitnami/bitnami-docker-minio#26]
**Description**
Not really an issue nor bug per se but, I'm trying to use docker for my storage solution using minio, this supports distributed mode which you can do locally using docker-compose. I'm trying to actually do use distributed mode across different sites for high availability purposes.
If that possible? 
I have 3 sites, one site has two nodes and the other two sites have one node each.
I've been trying a mixture of docker-compose values and here is my most recent below.
It does complain about not enough disks now (below), but using the config below from the documentation, it does not work correctly:
```      
- MINIO_DISTRIBUTED_NODES=site1-001.mydomain.com/data-{0...1},site1-002.mydomain.com/data-{0...1},site2-001.mydomain.com/data-{0...1},site3-001.mydomain.com/data-{0...1}
```
Error:
```
minio1_1  | ERROR Invalid command line arguments: Incorrect number of endpoints provided [http://site-001.mydomain.com/data-{0...1}]
minio1_1  |       > Please provide correct combination of local/remote paths
minio1_1  |       HINT:
minio1_1  |         For more information, please refer to https://docs.min.io/docs/minio-erasure-code-quickstart-guide
```

**site1-001 docker-compose.yml (all sites are the same config):**
```
version: '2'
services:
  minio1:
    image: 'bitnami/minio:latest'
    environment:
      - MINIO_ROOT_USER=minio-access-key
      - MINIO_ROOT_PASSWORD=minio-secret-key
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=site1-001.mydomain.com,site1-002.mydomain.com,site2-001.mydomain.com,site3-001.mydomain.com
      - MINIO_SKIP_CLIENT=yes
    ports:
      - 9000:9000
      - 9001:9001
    dns:
      - x.x.x.x
      - x.x.x.x
    dns_search:
      - mydomain.com
    network_mode: bridge
```

**Describe the results you received:**
```
minio1_1  | Unable to read 'format.json' from http://site1-001.mydomain.com:9000/data: Server expects 'storage' API version 'v40', instead found 'v40' - *rolling upgrade is not allowed* - please make sure all servers are running the same MinIO version (DEVELOPMENT.2021-09-24T00-24-24Z)     <<<< confirmed that all are sites using the same version
minio1_1  | 
minio1_1  | 
minio1_1  | API: SYSTEM()
minio1_1  | Time: 12:44:11 UTC 09/29/2021
minio1_1  | Error: Read failed. Insufficient number of disks online (*errors.errorString)
minio1_1  |        5: cmd/prepare-storage.go:268:cmd.connectLoadInitFormats()
minio1_1  |        4: cmd/prepare-storage.go:317:cmd.waitForFormatErasure()
minio1_1  |        3: cmd/erasure-server-pool.go:90:cmd.newErasureServerPools()
minio1_1  |        2: cmd/server-main.go:610:cmd.newObjectLayer()
minio1_1  |        1: cmd/server-main.go:527:cmd.serverMain()
minio1_1  | Waiting for a minimum of 2 disks to come online (elapsed 19m39s)
```

**Describe the results you expected:**
Each server to connect for HA.

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:53:39 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:00 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 5
  Running: 0
  Paused: 0
  Stopped: 5
 Images: 6
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.18.0-305.12.1.el8_4.x86_64
 Operating System: CentOS Linux 8
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 7.567GiB
 Name: myhost
 ID: xxxxxxxx
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Comment by miguelaeh** [comment]
Hi @tom0010 ,
If you are interested in using the distributed mode I recommend you to use our Minio Helm Chart: https://github.com/bitnami/charts/blob/master/bitnami/minio

There are also examples fo distributed docker-compose in this repo: https://github.com/bitnami/bitnami-docker-minio/blob/master/docker-compose-distributed.yml

Try removing the `/data` suffix in your URLs, I think that needs to be the Minio host.

**Comment by tom0010** [comment]
Hi @miguelaeh thanks for your reply. 
We don't have kubernetes unfortunately so it doesn't look like I could use the helm chart. 

I tried without the `/data` suffix, on the OP there is the example:
```
version: '2'
services:
  minio1:
    image: 'bitnami/minio:latest'
    environment:
      - MINIO_ROOT_USER=minio-access-key
      - MINIO_ROOT_PASSWORD=minio-secret-key
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=site1-001.mydomain.com,site1-002.mydomain.com,site2-001.mydomain.com,site3-001.mydomain.com
      - MINIO_SKIP_CLIENT=yes
    ports:
      - 9000:9000
      - 9001:9001
    dns:
      - x.x.x.x
      - x.x.x.x
    dns_search:
      - mydomain.com
    network_mode: bridge
```
But this actually complains about not enough disks, which is why I added the `/data` suffix after to test, which is here:
```
- MINIO_DISTRIBUTED_NODES=site1-001.mydomain.com/data-{0...1},site1-002.mydomain.com/data-{0...1},site2-001.mydomain.com/data-{0...1},site3-001.mydomain.com/data-{0...1}
```
If the example you gave, I tried to mimic that, but that is for 4 local containers, I am trying to get it working on different sites. Do you know if that is possible? If so I wonder what I am missing.
Thanks

**Comment by tom0010** [comment]
I actually have this working using the vanilla docker image. I couldn't get the `MINIO_DISTRIBUTED_NODES` value working, and I think there are some reasons why. It seems that your docker image hardcodes the port to `9000` which actually appends to the `node`, e.g. if I did `MINIO_DISTRIBUTED_NODES=site1-001.mydomain.com/data-{0...1}` it would return:
```
site1-001.mydomain.com/data-1:9000
site1-001.mydomain.com/data-2:9000
```
Whereas it should be the following... providing we are using the default port of `9000`:
```
site1-001.mydomain.com:9000/data-1
site1-001.mydomain.com:9000/data-2
```
I thought it was worth sharing my `docker-compose.yml` for the vanila image:
```
version: '3.2'
services:
  minio:
    image: minio/minio:RELEASE.2021-09-24T00-24-24Z
    container_name: minio
    volumes:
      - data1:/data1
      - data2:/data2
      - data3:/data3
      - data4:/data4
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_PROMETHEUS_AUTH_TYPE: public
      MINIO_ROOT_USER: test1234
      MINIO_ROOT_PASSWORD: test1234
    command: server --console-address ":9001" http://site1-001.mydomain.com:9000/data{1...4} http://site1-002.mydomain.com:9000/data{1...4} http://site2-001.mydomain.com:9000/data{1...4} http://site3-001.mydomain.com:9000/data{1...4}
    dns:
      - x.x.x.x
      - x.x.x.x
    dns_search:
      - mydomain.com
    network_mode: host
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
volumes:
  data1:
    driver: local
  data2:
    driver: local
  data3:
    driver: local
  data4:
    driver: local
```
To fix this error: 
```
minio1_1  | Unable to read 'format.json' from http://site1-001.mydomain.com:9000/data: Server expects 'storage' API version 'v40', instead found 'v40' - *rolling upgrade is not allowed* - please make sure all servers are running the same MinIO version (DEVELOPMENT.2021-09-24T00-24-24Z)
```
I had to make sure I was using `network_mode: host` which is broken in the latest docker-compose version, so I had to make sure I was running `1.26.2`. 
I also had to use 4 local drives per container as per a requirement from minio.

I do have one concern though, I was hoping that I could lose a site and the data would be persistent across all containers.
It seems that if I take down `site1-001` all other containers depend on that. 
Whereas if take down another container that is not `site1-001` everything run smoothly. It seems that `site1-001` is the "master" and all other containers depend on that node/container. Which is not really consistent from an HA point of view.
