### ISSUE TITLE
How run minio server on custom port?

### ISSUE THREAD

**Issue by kuksik** [bitnami/bitnami-docker-minio#28]
I need run minio on port e.g. 9003. I can not find how do it in the documentation. I have investigated codebase and looks like that i can use MINIO_API_PORT_NUMBER for it. But when i set this variable i get error:

```
API: SYSTEM()
Time: 18:49:12 UTC 09/29/2021
DeploymentID: 48a9618c-ed31-4e94-8ce4-76dfd6f6216e
Error: Access Denied. (*errors.errorString)
       requestHeaders={"method":"GET","reqURI":"/minio/admin/v3/info","header":{"Host":["localhost:9000"],"User-Agent":["MinIO (linux; amd64) madmin-go/0.0.1 mc/DEVELOPMENT.2021-09-23T06-13-33Z"],"X-Amz-Content-Sha256":["e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"]}}
       4: cmd/auth-handler.go:154:cmd.validateAdminSignature()
       3: cmd/auth-handler.go:165:cmd.checkAdminRequestAuth()
       2: cmd/admin-handlers.go:1956:cmd.adminAPIHandlers.ServerInfoHandler()
       1: net/http/server.go:2046:http.HandlerFunc.ServeHTTP()
 18:49:12.22 INFO  ==> MinIO is already stopped...
```

My docker compose file:

```
version: '3'

services:
  minio:
    container_name: minio
    image: bitnami/minio:latest
    ports:
      - 9005:9005
      - 9004:9004
    environment:
      - BITNAMI_DEBUG=true
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio
      - MINIO_API_PORT_NUMBER=9005
      - MINIO_CONSOLE_PORT_NUMBER=9004

    volumes:
      - /backups/minio/data:/data
```

Maybe i do something wrong but i can not understand what) Or it is bug.
