### ISSUE TITLE
default bucket doesn't exist 

### ISSUE THREAD

**Issue by shahinghasemi** [bitnami/bitnami-docker-minio#34]
**Description**
I'm using `MINIO_DEFAULT_BUCKETS` environment variable as a means to create the default bucket, however it seems it takes some time to create the bucket while container is up so the tests would fail.
**Steps to reproduce the issue:**

1. this is my docker-compose.test.yml:
```
version: '3.8'

services:
  minio:
    image: bitnami/minio:2021
    ports:
      - 127.0.0.1:9000:9000
      - 127.0.0.1:9001:9001
    environment:
      - MINIO_ACCESS_KEY=accessKey
      - MINIO_SECRET_KEY=secretKey123
      - MINIO_DEFAULT_BUCKETS=my-bucket

```

**What actually happens**

container is up while the bucket has not been created.

**What you expect to happen**
First the bucket should be created then after that the container should be up.
As a solution I put a `sleep 10` after `docker-compose up ...` to make sure that the bucket has been created.
