### ISSUE TITLE
Adding LDAP support

### ISSUE THREAD

**Issue by eclipsetalk** [bitnami/bitnami-docker-minio#38]
I'm trying to use LDAP with minio but it doesn't work. I don't even get any logs in the console.
This is my setting for my chart. What am I doing wrong:

```
extraEnv:
  - name: MINNIO_LOG_LEVEL
    value: DEBUG
  - name: MINIO_IDENTITY_LDAP_SERVER_ADDR
    value: "ldaps://xxxx.corp:636"
  - name: MINIO_IDENTITY_LDAP_GROUP_SEARCH_FILTER
    value: "(&(objectCategory=user)(sAMAccountName=%s))"
  - name: MINIO_IDENTITY_LDAP_USER_DN_SEARCH_BASE_DN
    value: "DC=xxx,DC=CORP"
  - name: MINIO_IDENTITY_LDAP_LOOKUP_BIND_PASSWORD
    value: 'xxxx'
  - name: MINIO_IDENTITY_LDAP_LOOKUP_BIND_DN
    value: "CN=xxxxx,OU=Svcaccts,DC=xxx,DC=CORP"
  - name: MINIO_IDENTITY_LDAP_GROUP_SEARCH_FILTER
    value: "(&(objectClass=group)(member=%d))"
```
