### ISSUE TITLE
container died if both env is set MINIO_REGION_NAME, MINIO_DEFAULT_BUCKETS

### ISSUE THREAD

**Issue by panteparak** [bitnami/bitnami-docker-minio#4]
**Description**

When both MINIO_DEFAULT_BUCKETS and MINIO_REGION_NAME is set, default bucket is failed to create then died

**Steps to reproduce the issue:**
### docker-compsoe
```
  minio:
    image: bitnami/minio
    ports:
      - 127.0.0.1:9000:9000
    environment:
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=password
      - MINIO_DEFAULT_BUCKETS=my-project
      - MINIO_BROWSER=on
      - MINIO_REGION_NAME=local
```

**Describe the results you received:**
### Error
`mc: <ERROR> Unable to make bucket `local/my-project`. The authorization header is malformed; the region is wrong; expecting 'us-east-1'.`

Log output
```
boost_minio |  19:55:47.39 Welcome to the Bitnami minio container
boost_minio |  19:55:47.40 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-minio
boost_minio |  19:55:47.40 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-minio/issues
boost_minio |  19:55:47.42 Send us your feedback at containers@bitnami.com
boost_minio |  19:55:47.42 
boost_minio |  19:55:47.42 INFO  ==> ** Starting MinIO setup **
boost_minio |  19:55:47.48 INFO  ==> Starting MinIO in background...
boost_minio |  19:55:57.48 INFO  ==> Adding local Minio host to 'mc' configuration...
boost_minio |  19:55:57.53 INFO  ==> Creating default buckets...
boost_minio | mc: <ERROR> Unable to make bucket `local/my-project`. The authorization header is malformed; the region is wrong; expecting 'us-east-1'.
boost_minio | /opt/bitnami/scripts/libminioclient.sh: line 70: args: readonly variable
boost_minio |  19:55:57.64 INFO  ==> MinIO is already stopped...
boost_minio exited with code 1

```
