### ISSUE TITLE
volume data not work

### ISSUE THREAD

**Issue by gromov-io** [bitnami/bitnami-docker-minio#50]
### Name and Version

bitnami/minio:latest

### What steps will reproduce the bug?

1. create docker-compose 
```yaml
version: '2'

services:
  minio:
    image: 'bitnami/minio:latest'
    user: root
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ACCESS_KEY=minio-access-key
      - MINIO_SECRET_KEY=minio-secret-key
    volumes:
      - '/media/s3:/data'

networks:
  default:
    external:
      name: proxy-network
```
2. run

### What is the expected behavior?

the container starts without errors

### What do you see instead?
```
error: failed switching to "minio": unable to find user minio: no matching entries in passwd file
```
### Additional information
OS: **Ubuntu 20.04.3 LTS**
![image](https://user-images.githubusercontent.com/46241127/154150781-59ae02a9-fa95-4491-b0fd-022f5b6cff85.png)
