### ISSUE TITLE
Cannot supply self-signed CA certificate to support OpenID configuration

### ISSUE THREAD

**Issue by chris-maclean** [bitnami/bitnami-docker-minio#51]
### Name and Version

10.0.0

### What steps will reproduce the bug?

I have Keycloak and MinIO running in a baremetal Kubernetes cluster. I'd like to make use of MinIO's [OpenID Connect](https://docs.min.io/minio/baremetal/security/openid-external-identity-management/configure-openid-external-identity-management.html#minio-authenticate-using-openid-generic) integration feature so my Keycloak users can use MinIO. I've followed the steps in the MinIO configuration page, but when I load the MinIO web console, it complains that the certificate cannot be verified. This makes some sense -- I'm using a self-signed certificate to support https access with Keycloak. That certificate isn't inherently trusted by the MinIO container. The MinIO console login page shows this error:

![image](https://user-images.githubusercontent.com/5133639/155185301-6a3d89b0-0604-4f75-af99-531a00ae86a5.png)

(I've replaced my real domain with `mydomain.com`. I'm confident that the domain on the certificate and the domain I'm trying to reach match)

Here's what I've done to try and make the cert trusted.

0a. I have a [`cert-manager` certificate](https://cert-manager.io/v0.12-docs/usage/certificate/) resource in my cluster. It owns a `Secret` with the following data

- ca.crt
- tls.crt
- tls.key

Keycloak presents `ca.crt` during TLS handshaking. I can visit the Keycloak admin console in my browser and get a "This site isn't safe" warning. After bypassing the warning, I can inspect the certificate and match the fingerprints and other properties to `ca.crt`. So I *know* that `ca.crt` is the cert that MinIO needs to trust.  

1. I added some `extraEnvVars` to the MinIO `values.yaml` to configure it to use OpenID. Those vars are:
```yaml
extraEnvVars: # these extra variables configure MinIO to authenticate requests with Keycloak
  - name: MINIO_IDENTITY_OPENID_CONFIG_URL
    value: "https://mydomain.com/auth/realms/myrealm/.well-known/openid-configuration"
  - name: MINIO_IDENTITY_OPENID_CLIENT_ID
    value: "my_client_id"
  - name: MINIO_IDENTITY_OPENID_CLIENT_SECRET
    value: "client-secret"
  - name: MINIO_IDENTITY_OPENID_CLAIM_NAME
    value: "claim_name"
```

2. I created a `ConfigMap` with the data of `ca.crt` -- call it `ca-crt-configmap`
3. I mounted `ca-crt-configmap` to the MinIO pods with the `extraVolumes` and `extraVolumeMounts` properties in `values.yaml`

```yaml
extraVolumes:
  - name: ca-crtstore
    configMap:
      name: ca-crt-configmap
extraVolumeMounts:
  - name: ca-crtstore
    mountPath: /usr/share/ca-certificates/selfsigned-ca.crt
    subPath: ca.crt
    readOnly: false
```

4. To test the certificate, I used the `curl` program installed in the MinIO container. **My hope is that if `curl` can successfully make a request to the `MINIO_IDENTITY_OPENID_CONFIG_URL`, then the MinIO server application will be able to do so as well**. Unfortunately, it did not work. `curl` reports that it failed to verify the legitimacy of the server.

```
$ curl $MINIO_IDENTITY_OPEN_ID_CONFIG_URL
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: unable to get local issuer certificate
``` 

`curl` even has a CLI option where you can specify the location of a CA cert: `--cacert [file]`. I tried using this option to point `curl` directly to my CA cert, and it *still* reports the same SSL certificate problem.

5. I did some further reading about installing CA certs and found that running `update-ca-certificates` or `dpkg-reconfigure ca-certificates` is required. This would not be acceptable for my Kubernetes use case, which needs to start up all MinIO pods without manual intervention, but I tried it just to see if it would work. I can see the new certificate get added to `/etc/ssl/certs/`, but I still get the same `curl` error.

6. I tried another experiment where I started up a different pod (running the baseline `amazonlinux` image) and mounted the configmap in the same way. On that pod, I can run 

```bash
curl --cacert /usr/share/ca-certificates/selfsigned-ca.crt $MINIO_IDENTITY_OPEN_ID_CONFIG_URL
```

and get back the correct response (a large JSON object describing the OpenID configuration). 

**This is what confuses me the most. Why does using the certificate on one pod work, but on another does not?** Is `curl` different between the two pods? This is why I reached out to the bitnami repo instead of MinIO itself -- I think my issue lies in something regarding the container image for MinIO.

One final question -- if using the certificate is too confusing or impossible, is there a way to disable the certificate check, similar to `curl -k`? [The MinIO docs](https://docs.min.io/minio/baremetal/reference/minio-server/minio-server.html#minio-server-envvar-external-identity-management-openid) show that other identity providers have a similar option (search `_TLS_SKIP_VERIFY`), but not OpenID.

### What is the expected behavior?

MinIO and other programs running in the container should be able to verify the certificate presented by my Keycloak instance.

### What do you see instead?

I'm doing my testing with `curl` because it enables more rapid turnaround. **My assumption is that if `curl` can access the HTTPS Keycloak endpoint, MinIO will be able to as well**. This assumption may be unfounded, but so far both programs exhibit the same kinds of errors.

`curl` shows this error from its verbose mode:

```
*   Trying 10.0.40.140...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x560935113fb0)
* Connected to mydomain.com (10.0.40.140) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: unable to get local issuer certificate
```

### Additional information

Ultimately, my question is -- what do I need to do to get the MinIO server container to trust my self-signed certificate? Failing that, can I disable the certificate check?
