### ISSUE TITLE
Unable to start as non-root with azure volume 

### ISSUE THREAD

**Issue by edrandall** [bitnami/bitnami-docker-minio#56]
### Name and Version

bitnami/minio:2022.4.1-debian-10-r5

### What steps will reproduce the bug?

1. Deploy in "standalone" mode to an azure environment - running as non-root (1001) with gid (0), with an existing persistence claim
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/environment: dev
    app.kubernetes.io/instance: minio
    app.kubernetes.io/name: minio
    helm.sh/chart: minio-11.2.8
  name: minio
  namespace: my-namespace
spec:
  selector:
    matchLabels:
      app.kubernetes.io/environment: dev
      app.kubernetes.io/instance: minio
      app.kubernetes.io/name: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/environment: dev
        app.kubernetes.io/instance: minio
        app.kubernetes.io/name: minio
        helm.sh/chart: minio-11.2.8
    spec:
      containers:
      - env:
        - name: BITNAMI_DEBUG
          value: "true"
        - name: MINIO_SCHEME
          value: http
        - name: MINIO_FORCE_NEW_KEYS
          value: "no"
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              key: root-user
              name: minio-s3
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: root-password
              name: minio-s3
        - name: MINIO_BROWSER
          value: "on"
        - name: MINIO_PROMETHEUS_AUTH_TYPE
          value: public
        - name: MINIO_CONSOLE_PORT_NUMBER
          value: "9001"
        image: bitnami/minio:2022.4.1-debian-10-r5
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /minio/health/live
            port: minio-api
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        name: minio
        ports:
        - containerPort: 9000
          name: minio-api
          protocol: TCP
        - containerPort: 9001
          name: minio-console
          protocol: TCP
        readinessProbe:
          failureThreshold: 5
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: minio-api
          timeoutSeconds: 1
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
        volumeMounts:
        - mountPath: /data
          name: data
      securityContext:
        fsGroup: 1001
      serviceAccountName: minio
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: minio
```
2. The persistentVolumeClaim:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
    volume.beta.kubernetes.io/storage-provisioner: file.csi.azure.com
  creationTimestamp: '2021-12-10T12:37:27Z'
  finalizers:
    - kubernetes.io/pvc-protection
  name: minio
  namespace: my-namespace
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 600Gi
  storageClassName: azurefile-csi
  volumeMode: Filesystem
```

3. The storage class (configured by our cloud team, not modifiable by me) of the volume uses the following mount options:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-csi
provisioner: file.csi.azure.com
allowVolumeExpansion: true
parameters:
  skuName: Standard_LRS
  resourceGroup: "my-rg"
  storageAccount: "my-sa"
  storeAccountKey: "false"
  useDataPlaneAPI: "true"
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict  # https://linux.die.net/man/8/mount.cifs
  - nosharesock  # reduce probability of reconnect race
  - actimeo=30  # reduce latency for metadata-heavy workload
```

### What is the expected behavior?

The minio container should start normally, running as user 1001.

### What do you see instead?

The minio container is unable to start, giving the following output and going into CrashLoopBackoff:
```
 15:25:12.69
 15:25:12.69 Welcome to the Bitnami minio container
 15:25:12.70 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-minio
 15:25:12.70 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-minio/issues
 15:25:12.70
 15:25:12.70 INFO  ==> ** Starting MinIO setup **
minio 15:25:12.72 DEBUG ==> Validating settings in MINIO_* env vars..
chmod: changing permissions of '/data/.root_user': Operation not permitted
chmod: changing permissions of '/data/.root_password': Operation not permitted
```

### Additional information

1. Adding an init-container (with same securityContext as minio) to check the configuration, gave this output:
```
+ id -a
uid=1001 gid=0(root) groups=0(root),1001

+ ls -la /data
total 5
drwxrwxrwx 2 root root    0 Dec 10 13:36 .
drwxr-xr-x 1 root root 4096 Apr 14 15:27 ..
drwxrwxrwx 2 root root    0 Dec 10 13:37 .minio.sys
-rwxrwxrwx 1 root root   11 Apr 14 15:27 .root_password
-rwxrwxrwx 1 root root   11 Apr 14 15:27 .root_user
drwxrwxrwx 2 root root    0 Dec 14 14:59 test-bucket

+ chmod 600 /data/.root_user /data/.root_password
chmod: changing permissions of '/data/.root_user': Operation not permitted
chmod: changing permissions of '/data/.root_password': Operation not permitted
```

2. The failure is due to the following line in scripts/libminio.sh `minio_regenerate_keys()`:
```
chmod 600 "${MINIO_DATA_DIR}/.root_user" "${MINIO_DATA_DIR}/.root_password"
```

3. Suggest the following change to minio_regenerate_keys() which would allow the container to start with these mount options:
Replace line 318:
```
    chmod 600 "${MINIO_DATA_DIR}/.root_user" "${MINIO_DATA_DIR}/.root_password"
```
With:
```
    if ! chmod 600 "${MINIO_DATA_DIR}/.root_user" "${MINIO_DATA_DIR}/.root_password" ; then
        warn "Unable to set secure permissions key files in ${MINIO_DATA_DIR}"
    fi
```
