### ISSUE TITLE
Default bucket policy not applied if folder exists

### ISSUE THREAD

**Issue by Ghirigoro** [bitnami/bitnami-docker-minio#61]
### Name and Version

bitnami/minio

### What steps will reproduce the bug?

1. Create a folder called `.build/assets/development/` in your project root
2. In docker-compose define a service like this:
```yaml
  minio:
    image: bitnami/minio
    container_name: minio
    platform: linux/amd64
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
      - MINIO_DEFAULT_BUCKETS=development:public
      - MINIO_FORCE_NEW_KEYS=yes
    volumes:
      - ./.build/assets:/data
```

NOTE: This was done on an M1 mac running MacOS 12.3.1

### What is the expected behavior?

 I expected that files in the development bucket would be accessible and the bucket would use the `public` policy.

### What do you see instead?

The `development` bucket is listed as `private` in the minio console and its contents cannot be accessed outside of the console (e.g. `http://localhost:9000/development/foo.baz` comes back with an access denied error).
