### ISSUE TITLE
Error in pod when deploying minio in Rancher

### ISSUE THREAD

**Issue by johnwc** [bitnami/bitnami-docker-minio#62]
### Name and Version

bitnami/minio 11.3.5

### What steps will reproduce the bug?

1. Add repo to cluster.
2. Install minio app from charts list using below changed settings.

```yaml
gateway:
  auth:
    azure:
      accessKey: '<randomGenKey>'
      secretKey: '<randomGenKey>'
      serviceEndpoint: '<storagename>.core.windows.net'
      storageAccountKey: '<storagekey>'
      storageAccountName: '<storagename>'
  enabled: true
  type: azure
service:
  nodePorts:
    api: 9000
    console: 9001
```

### What is the expected behavior?

Working deployed minio configured in gateway mode using azure storage.

### What do you see instead?

Pod log gives `‘azure’ is not a minio sub-command. See ‘minio --help’.`

### Additional information

Before seeing this repo existed, I opened issue up over at https://github.com/bitnami/charts/issues/10258 as well
