### ISSUE TITLE
Data Volume Not Mounting / Breaking in Latest?

### ISSUE THREAD

**Issue by steve-gray** [bitnami/bitnami-docker-minio#64]
### Name and Version

bitnami/minio:latest

### What steps will reproduce the bug?

Building in Harness CI (Drone/Enterprise) with the below has been working previously:

```yaml
                - identifier: minio
                  name: minio
                  type: Service
                  description: The Minio blob store.
                  spec:
                      connectorRef: org.Docker_Hub
                      image: bitnami/minio:latest
                      envVariables:
                          MINIO_ROOT_USER: ci-user
                          MINIO_ROOT_PASSWORD: ci-password
                          MINIO_CONSOLE_PORT_NUMBER: "9099"
                          BITNAMI_DEBUG: "true"
```

### What is the expected behavior?

Should start up cleanly with this set of parameters.

### What do you see instead?

Startup fail with:

```
INFO  ==> Starting MinIO in background...
Formatting 1st pool, 1 set(s), 1 drives per set.

API: SYSTEM()
Time: 21:00:45 UTC 06/02/2022
Error: Disk `/data` is part of root disk, will not be used (*errors.errorString)
       8: internal/logger/logger.go:278:logger.LogIf()
```
![image](https://user-images.githubusercontent.com/14563775/171738226-0112880b-93ff-417b-83f7-bf2a9d86ee66.png)

### Additional information

Reverting back to `bitnami/minio:2022.5.23` image appears to fix this.
