### ISSUE TITLE
Minio stop with:  is a root disk. Please ensure the disk is mounted properly, refusing to use root disk

### ISSUE THREAD

**Issue by fredbcode** [bitnami/bitnami-docker-minio#9]
Hello,

Minio is shutting down right after starting 

Here my docker-compose (swarm), I'm using the latest image
Four entries like this 

```
  minio1:                                                                                                                                                      
    image: bitnami/minio                                                                                                                                       
    hostname: minio1                                                                                                                                           
    volumes:                                                                                                                                                   
      - /datas/minio1:/data                                                                                                                                    
    ports:                                                                                                                                                     
      - "9001:9000"                                                                                                                                            
    networks:                                                                                                                                                  
      - inside                                                                                                                                                 
    environment:                                                                                                                                               
      - "MINIO_ACCESS_KEY=test"                                                                                                               
      - "MINIO_SECRET_KEY=test"                                                                                            
      - "MINIO_DISTRIBUTED_MODE_ENABLED=yes"                                                                                                                   
      - "BITNAMI_DEBUG=true"                                                                                                                                   
      - "MINIO_DISTRIBUTED_NODES=minio1,minio2,minio3,minio4"                                                                                                  
    deploy:                                                                                                                                                    
      placement:                                                                                                                                               
        constraints:                                                                                                                                           
          - "node.hostname == nostromo"                                                                                                                        
                                                                                                                                                               
  minio2:                                                                                                                                                      
    image: bitnami/minio                                                                                                                                       
    hostname: minio2                                                                                                                                           
    volumes:                                                                                                                                                   
      - /datas/minio1:/data                                                                                                                                    
    networks:                                                                                                                                                  
      - inside                                                                                                                                                 
    environment:                                                                                                                                               
      - "MINIO_ACCESS_KEY=test"                                                                                                               
      - "MINIO_SECRET_KEY=test"                                                                                            
      - "MINIO_DISTRIBUTED_MODE_ENABLED=yes"                                                                                                                   
      - "MINIO_DISTRIBUTED_NODES=minio1,minio2,minio3,minio4"                                                                                                  
    deploy:                                                                                                                                                    
      placement:                                                                                                                                               
        constraints:                                                                                                                                           
          - "node.hostname == nostromo"        
```                                                                                                                

Debug

```
cluster_minio1.1.mvzsdhszh2mt@nostromo    |  16:20:20.79 INFO  ==> MinIO is already stopped...
cluster_minio1.1.htbfae2byn4a@nostromo    |  16:20:28.72 
cluster_minio1.1.htbfae2byn4a@nostromo    |  16:20:28.73 Welcome to the Bitnami minio container
cluster_minio1.1.htbfae2byn4a@nostromo    |  16:20:28.73 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-minio
cluster_minio1.1.htbfae2byn4a@nostromo    |  16:20:28.74 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-minio/issues
cluster_minio1.1.htbfae2byn4a@nostromo    |  16:20:28.74 
cluster_minio1.1.htbfae2byn4a@nostromo    |  16:20:28.75 INFO  ==> ** Starting MinIO setup **
cluster_minio1.1.htbfae2byn4a@nostromo    |  16:20:28.80 DEBUG ==> Validating settings in MINIO_* env vars..
cluster_minio1.1.htbfae2byn4a@nostromo    |  16:20:28.84 INFO  ==> Starting MinIO in background...
cluster_minio1.1.htbfae2byn4a@nostromo    | Disk `/data` is a root disk. Please ensure the disk is mounted properly, refusing to use root disk.                
cluster_minio1.1.htbfae2byn4a@nostromo    | Disk `http://minio2:9000/data` is a root disk. Please ensure the disk is mounted properly, refusing to use root dis
k.                                                                                                                                                             
cluster_minio1.1.htbfae2byn4a@nostromo    | Waiting for a minimum of 2 disks to come online (elapsed 1s)                                                       
cluster_minio1.1.htbfae2byn4a@nostromo    |                                                                                                                    
cluster_minio1.1.htbfae2byn4a@nostromo    | Disk `/data` is a root disk. Please ensure the disk is mounted properly, refusing to use root disk.                
cluster_minio1.1.htbfae2byn4a@nostromo    | Disk `http://minio2:9000/data` is a root disk. Please ensure the disk is mounted properly, refusing to use root dis
k.                                                                                                                                                             
cluster_minio1.1.htbfae2byn4a@nostromo    | Waiting for a minimum of 2 disks to come online (elapsed 1s)                                                       
cluster_minio1.1.htbfae2byn4a@nostromo    |                                                                                                                    
cluster_minio1.1.htbfae2byn4a@nostromo    | Disk `/data` is a root disk. Please ensure the disk is mounted properly, refusing to use root disk.                
cluster_minio1.1.htbfae2byn4a@nostromo    | Disk `http://minio2:9000/data` is a root disk. Please ensure the disk is mounted properly, refusing to use root dis
k.                                                                                                                                                             
cluster_minio1.1.htbfae2byn4a@nostromo    | Waiting for a minimum of 2 disks to come online (elapsed 2s)                                                       
cluster_minio1.1.htbfae2byn4a@nostromo    |                                                                                                                    
cluster_minio1.1.htbfae2byn4a@nostromo    | Disk `/data` is a root disk. Please ensure the disk is mounted properly, refusing to use root disk.                
cluster_minio1.1.htbfae2byn4a@nostromo    | Disk `http://minio2:9000/data` is a root disk. Please ensure the disk is mounted properly, refusing to use root dis
k.                                                                                                                                                             
cluster_minio1.1.htbfae2byn4a@nostromo    | Waiting for a minimum of 2 disks to come online (elapsed 2s)                                                       
cluster_minio1.1.htbfae2byn4a@nostromo    |                                                                                                                    
cluster_minio1.1.htbfae2byn4a@nostromo    | Disk `/data` is a root disk. Please ensure the disk is mounted properly, refusing to use root disk.                
cluster_minio1.1.htbfae2byn4a@nostromo    | Disk `http://minio2:9000/data` is a root disk. Please ensure the disk is mounted properly, refusing to use root dis
k.                                                                                                                                                             
cluster_minio1.1.htbfae2byn4a@nostromo    | Waiting for a minimum of 2 disks to come online (elapsed 3s)                                                       
cluster_minio1.1.htbfae2byn4a@nostromo    |                                                                                                                    
cluster_minio1.1.htbfae2byn4a@nostromo    | Disk `/data` is a root disk. Please ensure the disk is mounted properly, refusing to use root disk.                
cluster_minio1.1.htbfae2byn4a@nostromo    | Disk `http://minio2:9000/data` is a root disk. Please ensure the disk is mounted properly, refusing to use root dis
                                                                                                                                                           

```
Permissions 

drwxrwxr-x  16  472 docker         4096 Sep  3 17:02 datas
Inside
drwx------  2 1001          root     4096 Sep  3 18:25 minio1 

Maybe I missed something ?

Thanks
